spring.application.name=resumeanalyzer

spring.config.import=optional:file:./src/main/resources/application-local.properties

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB